language: android
android:
  components:
  # include `tools` because travis requires it: https://github.com/travis-ci/travis-ci/issues/5036
  - tools
  - build-tools-23.0.3
  - android-23
before_script:
  - export COLLECT_VERSION_NAME="0.1.$TRAVIS_BUILD_NUMBER"
  - nvm install 4.4.5
  - nvm use 4.4.5
  - npm install -g grunt
  - npm install
script:
  make travis
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: android/build/outputs/apk/enketo-collect-SNAPSHOT-debug.apk
  skip_cleanup: true
  on:
    tags: true
