language: android
branches:
  only:
  - master
android:
  components:
  - build-tools-22.0.1
  - android-22
before_script:
  - export COLLECT_VERSION_NAME="0.1.$TRAVIS_BUILD_NUMBER"
  - npm install
script:
  make travis
